// flow-typed signature: 2813c04834e5c9fbdd75a2ea82386f02
// flow-typed version: <<STUB>>/airbrake_v0.3.x/flow_v0.40.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'airbrake'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'airbrake' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'airbrake/lib/airbrake' {
  declare module.exports: any;
}

declare module 'airbrake/test/common' {
  declare module.exports: any;
}

declare module 'airbrake/test/fast/test-express-handler' {
  declare module.exports: any;
}

declare module 'airbrake/test/fast/test-handle-exceptions' {
  declare module.exports: any;
}

declare module 'airbrake/test/fast/test-host' {
  declare module.exports: any;
}

declare module 'airbrake/test/fast/test-request-vars' {
  declare module.exports: any;
}

declare module 'airbrake/test/run' {
  declare module.exports: any;
}

declare module 'airbrake/test/slow/test-custom-request-options' {
  declare module.exports: any;
}

declare module 'airbrake/test/slow/test-environment' {
  declare module.exports: any;
}

declare module 'airbrake/test/slow/test-error-event' {
  declare module.exports: any;
}

declare module 'airbrake/test/slow/test-handle-exceptions' {
  declare module.exports: any;
}

declare module 'airbrake/test/slow/test-invalid-api-key' {
  declare module.exports: any;
}

declare module 'airbrake/test/slow/test-notify' {
  declare module.exports: any;
}

declare module 'airbrake/test/slow/test-throw-undefined' {
  declare module.exports: any;
}

declare module 'airbrake/test/slow/test-track-deployment' {
  declare module.exports: any;
}

// Filename aliases
declare module 'airbrake/index' {
  declare module.exports: $Exports<'airbrake'>;
}
declare module 'airbrake/index.js' {
  declare module.exports: $Exports<'airbrake'>;
}
declare module 'airbrake/lib/airbrake.js' {
  declare module.exports: $Exports<'airbrake/lib/airbrake'>;
}
declare module 'airbrake/test/common.js' {
  declare module.exports: $Exports<'airbrake/test/common'>;
}
declare module 'airbrake/test/fast/test-express-handler.js' {
  declare module.exports: $Exports<'airbrake/test/fast/test-express-handler'>;
}
declare module 'airbrake/test/fast/test-handle-exceptions.js' {
  declare module.exports: $Exports<'airbrake/test/fast/test-handle-exceptions'>;
}
declare module 'airbrake/test/fast/test-host.js' {
  declare module.exports: $Exports<'airbrake/test/fast/test-host'>;
}
declare module 'airbrake/test/fast/test-request-vars.js' {
  declare module.exports: $Exports<'airbrake/test/fast/test-request-vars'>;
}
declare module 'airbrake/test/run.js' {
  declare module.exports: $Exports<'airbrake/test/run'>;
}
declare module 'airbrake/test/slow/test-custom-request-options.js' {
  declare module.exports: $Exports<'airbrake/test/slow/test-custom-request-options'>;
}
declare module 'airbrake/test/slow/test-environment.js' {
  declare module.exports: $Exports<'airbrake/test/slow/test-environment'>;
}
declare module 'airbrake/test/slow/test-error-event.js' {
  declare module.exports: $Exports<'airbrake/test/slow/test-error-event'>;
}
declare module 'airbrake/test/slow/test-handle-exceptions.js' {
  declare module.exports: $Exports<'airbrake/test/slow/test-handle-exceptions'>;
}
declare module 'airbrake/test/slow/test-invalid-api-key.js' {
  declare module.exports: $Exports<'airbrake/test/slow/test-invalid-api-key'>;
}
declare module 'airbrake/test/slow/test-notify.js' {
  declare module.exports: $Exports<'airbrake/test/slow/test-notify'>;
}
declare module 'airbrake/test/slow/test-throw-undefined.js' {
  declare module.exports: $Exports<'airbrake/test/slow/test-throw-undefined'>;
}
declare module 'airbrake/test/slow/test-track-deployment.js' {
  declare module.exports: $Exports<'airbrake/test/slow/test-track-deployment'>;
}
