// flow-typed signature: 9220cfd0427e60f16ed0b4ab25071a7a
// flow-typed version: <<STUB>>/async_v0.2.x/flow_v0.40.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'async'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'async' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'async/lib/async' {
  declare module.exports: any;
}

// Filename aliases
declare module 'async/lib/async.js' {
  declare module.exports: $Exports<'async/lib/async'>;
}
