// flow-typed signature: 17ebc605535eb93a5a15fe55e80ff638
// flow-typed version: <<STUB>>/freelist_v^1.0.3/flow_v0.40.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'freelist'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'freelist' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'freelist/index' {
  declare module.exports: $Exports<'freelist'>;
}
declare module 'freelist/index.js' {
  declare module.exports: $Exports<'freelist'>;
}
