// flow-typed signature: 30c89096e3c4306212caad4e547924e3
// flow-typed version: <<STUB>>/json-schema_v0.2.x/flow_v0.40.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'json-schema'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'json-schema' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'json-schema/lib/links' {
  declare module.exports: any;
}

declare module 'json-schema/lib/validate' {
  declare module.exports: any;
}

declare module 'json-schema/test/tests' {
  declare module.exports: any;
}

// Filename aliases
declare module 'json-schema/lib/links.js' {
  declare module.exports: $Exports<'json-schema/lib/links'>;
}
declare module 'json-schema/lib/validate.js' {
  declare module.exports: $Exports<'json-schema/lib/validate'>;
}
declare module 'json-schema/test/tests.js' {
  declare module.exports: $Exports<'json-schema/test/tests'>;
}
