// flow-typed signature: c80093942351ef4d0d9917bc773ca63e
// flow-typed version: <<STUB>>/lodash_v2.4.x/flow_v0.40.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lodash'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'lodash' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'lodash/dist/lodash.compat' {
  declare module.exports: any;
}

declare module 'lodash/dist/lodash.compat.min' {
  declare module.exports: any;
}

declare module 'lodash/dist/lodash' {
  declare module.exports: any;
}

declare module 'lodash/dist/lodash.min' {
  declare module.exports: any;
}

declare module 'lodash/dist/lodash.underscore' {
  declare module.exports: any;
}

declare module 'lodash/dist/lodash.underscore.min' {
  declare module.exports: any;
}

declare module 'lodash/lodash' {
  declare module.exports: any;
}

// Filename aliases
declare module 'lodash/dist/lodash.compat.js' {
  declare module.exports: $Exports<'lodash/dist/lodash.compat'>;
}
declare module 'lodash/dist/lodash.compat.min.js' {
  declare module.exports: $Exports<'lodash/dist/lodash.compat.min'>;
}
declare module 'lodash/dist/lodash.js' {
  declare module.exports: $Exports<'lodash/dist/lodash'>;
}
declare module 'lodash/dist/lodash.min.js' {
  declare module.exports: $Exports<'lodash/dist/lodash.min'>;
}
declare module 'lodash/dist/lodash.underscore.js' {
  declare module.exports: $Exports<'lodash/dist/lodash.underscore'>;
}
declare module 'lodash/dist/lodash.underscore.min.js' {
  declare module.exports: $Exports<'lodash/dist/lodash.underscore.min'>;
}
declare module 'lodash/lodash.js' {
  declare module.exports: $Exports<'lodash/lodash'>;
}
