// flow-typed signature: 9590c332c8c0ebda01e9280a4d380b6e
// flow-typed version: <<STUB>>/nodemailer_v0.3.x/flow_v0.40.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'nodemailer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'nodemailer' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'nodemailer/examples/example_alternative' {
  declare module.exports: any;
}

declare module 'nodemailer/examples/example_autoembedding' {
  declare module.exports: any;
}

declare module 'nodemailer/examples/example_dkim' {
  declare module.exports: any;
}

declare module 'nodemailer/examples/example_sendmail' {
  declare module.exports: any;
}

declare module 'nodemailer/examples/example_ses' {
  declare module.exports: any;
}

declare module 'nodemailer/examples/example_smtp' {
  declare module.exports: any;
}

declare module 'nodemailer/examples/example_xoauth' {
  declare module.exports: any;
}

declare module 'nodemailer/examples/example_xoauth2' {
  declare module.exports: any;
}

declare module 'nodemailer/lib/engines/sendmail' {
  declare module.exports: any;
}

declare module 'nodemailer/lib/engines/ses' {
  declare module.exports: any;
}

declare module 'nodemailer/lib/engines/smtp' {
  declare module.exports: any;
}

declare module 'nodemailer/lib/engines/stub' {
  declare module.exports: any;
}

declare module 'nodemailer/lib/helpers' {
  declare module.exports: any;
}

declare module 'nodemailer/lib/nodemailer' {
  declare module.exports: any;
}

declare module 'nodemailer/lib/transport' {
  declare module.exports: any;
}

declare module 'nodemailer/lib/wellknown' {
  declare module.exports: any;
}

declare module 'nodemailer/lib/xoauth' {
  declare module.exports: any;
}

declare module 'nodemailer/test/nodemailer' {
  declare module.exports: any;
}

// Filename aliases
declare module 'nodemailer/examples/example_alternative.js' {
  declare module.exports: $Exports<'nodemailer/examples/example_alternative'>;
}
declare module 'nodemailer/examples/example_autoembedding.js' {
  declare module.exports: $Exports<'nodemailer/examples/example_autoembedding'>;
}
declare module 'nodemailer/examples/example_dkim.js' {
  declare module.exports: $Exports<'nodemailer/examples/example_dkim'>;
}
declare module 'nodemailer/examples/example_sendmail.js' {
  declare module.exports: $Exports<'nodemailer/examples/example_sendmail'>;
}
declare module 'nodemailer/examples/example_ses.js' {
  declare module.exports: $Exports<'nodemailer/examples/example_ses'>;
}
declare module 'nodemailer/examples/example_smtp.js' {
  declare module.exports: $Exports<'nodemailer/examples/example_smtp'>;
}
declare module 'nodemailer/examples/example_xoauth.js' {
  declare module.exports: $Exports<'nodemailer/examples/example_xoauth'>;
}
declare module 'nodemailer/examples/example_xoauth2.js' {
  declare module.exports: $Exports<'nodemailer/examples/example_xoauth2'>;
}
declare module 'nodemailer/lib/engines/sendmail.js' {
  declare module.exports: $Exports<'nodemailer/lib/engines/sendmail'>;
}
declare module 'nodemailer/lib/engines/ses.js' {
  declare module.exports: $Exports<'nodemailer/lib/engines/ses'>;
}
declare module 'nodemailer/lib/engines/smtp.js' {
  declare module.exports: $Exports<'nodemailer/lib/engines/smtp'>;
}
declare module 'nodemailer/lib/engines/stub.js' {
  declare module.exports: $Exports<'nodemailer/lib/engines/stub'>;
}
declare module 'nodemailer/lib/helpers.js' {
  declare module.exports: $Exports<'nodemailer/lib/helpers'>;
}
declare module 'nodemailer/lib/nodemailer.js' {
  declare module.exports: $Exports<'nodemailer/lib/nodemailer'>;
}
declare module 'nodemailer/lib/transport.js' {
  declare module.exports: $Exports<'nodemailer/lib/transport'>;
}
declare module 'nodemailer/lib/wellknown.js' {
  declare module.exports: $Exports<'nodemailer/lib/wellknown'>;
}
declare module 'nodemailer/lib/xoauth.js' {
  declare module.exports: $Exports<'nodemailer/lib/xoauth'>;
}
declare module 'nodemailer/test/nodemailer.js' {
  declare module.exports: $Exports<'nodemailer/test/nodemailer'>;
}
