// flow-typed signature: 3f7c35df8266d8e579d968033968b730
// flow-typed version: <<STUB>>/rand-token_v~0.2.1/flow_v0.40.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rand-token'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'rand-token' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'rand-token/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'rand-token/index' {
  declare module.exports: $Exports<'rand-token'>;
}
declare module 'rand-token/index.js' {
  declare module.exports: $Exports<'rand-token'>;
}
declare module 'rand-token/test/test.js' {
  declare module.exports: $Exports<'rand-token/test/test'>;
}
