// flow-typed signature: e21acffda2ce98a87ecac80085955490
// flow-typed version: <<STUB>>/readyness_v0.1.x/flow_v0.40.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'readyness'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'readyness' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'readyness/lib/readyness' {
  declare module.exports: any;
}

declare module 'readyness/wait/mocha' {
  declare module.exports: any;
}

// Filename aliases
declare module 'readyness/lib/readyness.js' {
  declare module.exports: $Exports<'readyness/lib/readyness'>;
}
declare module 'readyness/wait/mocha.js' {
  declare module.exports: $Exports<'readyness/wait/mocha'>;
}
