// flow-typed signature: 6f37806721bb9fa020b28d7aa7c89c45
// flow-typed version: <<STUB>>/redis_v0.12.x/flow_v0.40.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redis'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'redis' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'redis/connection_breaker' {
  declare module.exports: any;
}

declare module 'redis/lib/commands' {
  declare module.exports: any;
}

declare module 'redis/lib/parser/hiredis' {
  declare module.exports: any;
}

declare module 'redis/lib/parser/javascript' {
  declare module.exports: any;
}

declare module 'redis/lib/queue' {
  declare module.exports: any;
}

declare module 'redis/lib/to_array' {
  declare module.exports: any;
}

declare module 'redis/lib/util' {
  declare module.exports: any;
}

// Filename aliases
declare module 'redis/connection_breaker.js' {
  declare module.exports: $Exports<'redis/connection_breaker'>;
}
declare module 'redis/index' {
  declare module.exports: $Exports<'redis'>;
}
declare module 'redis/index.js' {
  declare module.exports: $Exports<'redis'>;
}
declare module 'redis/lib/commands.js' {
  declare module.exports: $Exports<'redis/lib/commands'>;
}
declare module 'redis/lib/parser/hiredis.js' {
  declare module.exports: $Exports<'redis/lib/parser/hiredis'>;
}
declare module 'redis/lib/parser/javascript.js' {
  declare module.exports: $Exports<'redis/lib/parser/javascript'>;
}
declare module 'redis/lib/queue.js' {
  declare module.exports: $Exports<'redis/lib/queue'>;
}
declare module 'redis/lib/to_array.js' {
  declare module.exports: $Exports<'redis/lib/to_array'>;
}
declare module 'redis/lib/util.js' {
  declare module.exports: $Exports<'redis/lib/util'>;
}
