// flow-typed signature: 0ca0ea941a4ca15c1f8c1aaa60be1a6e
// flow-typed version: <<STUB>>/semver_v1.1.4/flow_v0.40.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'semver'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'semver' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'semver/semver' {
  declare module.exports: any;
}

declare module 'semver/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'semver/semver.js' {
  declare module.exports: $Exports<'semver/semver'>;
}
declare module 'semver/test.js' {
  declare module.exports: $Exports<'semver/test'>;
}
