// flow-typed signature: 2816d8ca495a371cf5d6df5d6df86e9c
// flow-typed version: <<STUB>>/should_v3.3.1/flow_v0.40.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'should'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'should' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'should/lib/browser' {
  declare module.exports: any;
}

declare module 'should/lib/eql' {
  declare module.exports: any;
}

declare module 'should/lib/ext/assert' {
  declare module.exports: any;
}

declare module 'should/lib/ext/bool' {
  declare module.exports: any;
}

declare module 'should/lib/ext/browser/jquery' {
  declare module.exports: any;
}

declare module 'should/lib/ext/chain' {
  declare module.exports: any;
}

declare module 'should/lib/ext/deprecated' {
  declare module.exports: any;
}

declare module 'should/lib/ext/eql' {
  declare module.exports: any;
}

declare module 'should/lib/ext/error' {
  declare module.exports: any;
}

declare module 'should/lib/ext/http' {
  declare module.exports: any;
}

declare module 'should/lib/ext/match' {
  declare module.exports: any;
}

declare module 'should/lib/ext/number' {
  declare module.exports: any;
}

declare module 'should/lib/ext/property' {
  declare module.exports: any;
}

declare module 'should/lib/ext/string' {
  declare module.exports: any;
}

declare module 'should/lib/ext/type' {
  declare module.exports: any;
}

declare module 'should/lib/node' {
  declare module.exports: any;
}

declare module 'should/lib/should' {
  declare module.exports: any;
}

declare module 'should/lib/util' {
  declare module.exports: any;
}

declare module 'should/should' {
  declare module.exports: any;
}

declare module 'should/should.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'should/index' {
  declare module.exports: $Exports<'should'>;
}
declare module 'should/index.js' {
  declare module.exports: $Exports<'should'>;
}
declare module 'should/lib/browser.js' {
  declare module.exports: $Exports<'should/lib/browser'>;
}
declare module 'should/lib/eql.js' {
  declare module.exports: $Exports<'should/lib/eql'>;
}
declare module 'should/lib/ext/assert.js' {
  declare module.exports: $Exports<'should/lib/ext/assert'>;
}
declare module 'should/lib/ext/bool.js' {
  declare module.exports: $Exports<'should/lib/ext/bool'>;
}
declare module 'should/lib/ext/browser/jquery.js' {
  declare module.exports: $Exports<'should/lib/ext/browser/jquery'>;
}
declare module 'should/lib/ext/chain.js' {
  declare module.exports: $Exports<'should/lib/ext/chain'>;
}
declare module 'should/lib/ext/deprecated.js' {
  declare module.exports: $Exports<'should/lib/ext/deprecated'>;
}
declare module 'should/lib/ext/eql.js' {
  declare module.exports: $Exports<'should/lib/ext/eql'>;
}
declare module 'should/lib/ext/error.js' {
  declare module.exports: $Exports<'should/lib/ext/error'>;
}
declare module 'should/lib/ext/http.js' {
  declare module.exports: $Exports<'should/lib/ext/http'>;
}
declare module 'should/lib/ext/match.js' {
  declare module.exports: $Exports<'should/lib/ext/match'>;
}
declare module 'should/lib/ext/number.js' {
  declare module.exports: $Exports<'should/lib/ext/number'>;
}
declare module 'should/lib/ext/property.js' {
  declare module.exports: $Exports<'should/lib/ext/property'>;
}
declare module 'should/lib/ext/string.js' {
  declare module.exports: $Exports<'should/lib/ext/string'>;
}
declare module 'should/lib/ext/type.js' {
  declare module.exports: $Exports<'should/lib/ext/type'>;
}
declare module 'should/lib/node.js' {
  declare module.exports: $Exports<'should/lib/node'>;
}
declare module 'should/lib/should.js' {
  declare module.exports: $Exports<'should/lib/should'>;
}
declare module 'should/lib/util.js' {
  declare module.exports: $Exports<'should/lib/util'>;
}
declare module 'should/should.js' {
  declare module.exports: $Exports<'should/should'>;
}
declare module 'should/should.min.js' {
  declare module.exports: $Exports<'should/should.min'>;
}
