// flow-typed signature: 26016571a035ed8c200230c6e4502905
// flow-typed version: <<STUB>>/underscore.string_v2.2.x/flow_v0.40.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'underscore.string'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'underscore.string' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'underscore.string/dist/underscore.string.min' {
  declare module.exports: any;
}

declare module 'underscore.string/lib/underscore.string' {
  declare module.exports: any;
}

declare module 'underscore.string/test/run-qunit' {
  declare module.exports: any;
}

declare module 'underscore.string/test/speed' {
  declare module.exports: any;
}

declare module 'underscore.string/test/strings_standalone' {
  declare module.exports: any;
}

declare module 'underscore.string/test/strings' {
  declare module.exports: any;
}

declare module 'underscore.string/test/test_underscore/arrays' {
  declare module.exports: any;
}

declare module 'underscore.string/test/test_underscore/chaining' {
  declare module.exports: any;
}

declare module 'underscore.string/test/test_underscore/collections' {
  declare module.exports: any;
}

declare module 'underscore.string/test/test_underscore/functions' {
  declare module.exports: any;
}

declare module 'underscore.string/test/test_underscore/objects' {
  declare module.exports: any;
}

declare module 'underscore.string/test/test_underscore/speed' {
  declare module.exports: any;
}

declare module 'underscore.string/test/test_underscore/temp' {
  declare module.exports: any;
}

declare module 'underscore.string/test/test_underscore/utility' {
  declare module.exports: any;
}

declare module 'underscore.string/test/test_underscore/vendor/jquery' {
  declare module.exports: any;
}

declare module 'underscore.string/test/test_underscore/vendor/jslitmus' {
  declare module.exports: any;
}

declare module 'underscore.string/test/test_underscore/vendor/qunit' {
  declare module.exports: any;
}

declare module 'underscore.string/test/underscore' {
  declare module.exports: any;
}

// Filename aliases
declare module 'underscore.string/dist/underscore.string.min.js' {
  declare module.exports: $Exports<'underscore.string/dist/underscore.string.min'>;
}
declare module 'underscore.string/lib/underscore.string.js' {
  declare module.exports: $Exports<'underscore.string/lib/underscore.string'>;
}
declare module 'underscore.string/test/run-qunit.js' {
  declare module.exports: $Exports<'underscore.string/test/run-qunit'>;
}
declare module 'underscore.string/test/speed.js' {
  declare module.exports: $Exports<'underscore.string/test/speed'>;
}
declare module 'underscore.string/test/strings_standalone.js' {
  declare module.exports: $Exports<'underscore.string/test/strings_standalone'>;
}
declare module 'underscore.string/test/strings.js' {
  declare module.exports: $Exports<'underscore.string/test/strings'>;
}
declare module 'underscore.string/test/test_underscore/arrays.js' {
  declare module.exports: $Exports<'underscore.string/test/test_underscore/arrays'>;
}
declare module 'underscore.string/test/test_underscore/chaining.js' {
  declare module.exports: $Exports<'underscore.string/test/test_underscore/chaining'>;
}
declare module 'underscore.string/test/test_underscore/collections.js' {
  declare module.exports: $Exports<'underscore.string/test/test_underscore/collections'>;
}
declare module 'underscore.string/test/test_underscore/functions.js' {
  declare module.exports: $Exports<'underscore.string/test/test_underscore/functions'>;
}
declare module 'underscore.string/test/test_underscore/objects.js' {
  declare module.exports: $Exports<'underscore.string/test/test_underscore/objects'>;
}
declare module 'underscore.string/test/test_underscore/speed.js' {
  declare module.exports: $Exports<'underscore.string/test/test_underscore/speed'>;
}
declare module 'underscore.string/test/test_underscore/temp.js' {
  declare module.exports: $Exports<'underscore.string/test/test_underscore/temp'>;
}
declare module 'underscore.string/test/test_underscore/utility.js' {
  declare module.exports: $Exports<'underscore.string/test/test_underscore/utility'>;
}
declare module 'underscore.string/test/test_underscore/vendor/jquery.js' {
  declare module.exports: $Exports<'underscore.string/test/test_underscore/vendor/jquery'>;
}
declare module 'underscore.string/test/test_underscore/vendor/jslitmus.js' {
  declare module.exports: $Exports<'underscore.string/test/test_underscore/vendor/jslitmus'>;
}
declare module 'underscore.string/test/test_underscore/vendor/qunit.js' {
  declare module.exports: $Exports<'underscore.string/test/test_underscore/vendor/qunit'>;
}
declare module 'underscore.string/test/underscore.js' {
  declare module.exports: $Exports<'underscore.string/test/underscore'>;
}
