// flow-typed signature: 9b03d5c6156b06b2f00f67dd8c1ae305
// flow-typed version: <<STUB>>/winston_v0.6.x/flow_v0.40.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'winston'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'winston' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'winston/examples/couchdb' {
  declare module.exports: any;
}

declare module 'winston/examples/exception' {
  declare module.exports: any;
}

declare module 'winston/examples/raw-mode' {
  declare module.exports: any;
}

declare module 'winston/examples/webhook-post' {
  declare module.exports: any;
}

declare module 'winston/lib/winston' {
  declare module.exports: any;
}

declare module 'winston/lib/winston/common' {
  declare module.exports: any;
}

declare module 'winston/lib/winston/config' {
  declare module.exports: any;
}

declare module 'winston/lib/winston/config/cli-config' {
  declare module.exports: any;
}

declare module 'winston/lib/winston/config/npm-config' {
  declare module.exports: any;
}

declare module 'winston/lib/winston/config/syslog-config' {
  declare module.exports: any;
}

declare module 'winston/lib/winston/container' {
  declare module.exports: any;
}

declare module 'winston/lib/winston/exception' {
  declare module.exports: any;
}

declare module 'winston/lib/winston/logger' {
  declare module.exports: any;
}

declare module 'winston/lib/winston/transports' {
  declare module.exports: any;
}

declare module 'winston/lib/winston/transports/console' {
  declare module.exports: any;
}

declare module 'winston/lib/winston/transports/file' {
  declare module.exports: any;
}

declare module 'winston/lib/winston/transports/http' {
  declare module.exports: any;
}

declare module 'winston/lib/winston/transports/transport' {
  declare module.exports: any;
}

declare module 'winston/lib/winston/transports/webhook' {
  declare module.exports: any;
}

declare module 'winston/test/cli-test' {
  declare module.exports: any;
}

declare module 'winston/test/container-test' {
  declare module.exports: any;
}

declare module 'winston/test/custom-timestamp-test' {
  declare module.exports: any;
}

declare module 'winston/test/exception-test' {
  declare module.exports: any;
}

declare module 'winston/test/fixtures/scripts/default-exceptions' {
  declare module.exports: any;
}

declare module 'winston/test/fixtures/scripts/exit-on-error' {
  declare module.exports: any;
}

declare module 'winston/test/fixtures/scripts/log-exceptions' {
  declare module.exports: any;
}

declare module 'winston/test/fixtures/scripts/unhandle-exceptions' {
  declare module.exports: any;
}

declare module 'winston/test/helpers' {
  declare module.exports: any;
}

declare module 'winston/test/log-exception-test' {
  declare module.exports: any;
}

declare module 'winston/test/log-rewriter-test' {
  declare module.exports: any;
}

declare module 'winston/test/logger-test' {
  declare module.exports: any;
}

declare module 'winston/test/transports/console-test' {
  declare module.exports: any;
}

declare module 'winston/test/transports/file-maxfiles-test' {
  declare module.exports: any;
}

declare module 'winston/test/transports/file-maxsize-test' {
  declare module.exports: any;
}

declare module 'winston/test/transports/file-test' {
  declare module.exports: any;
}

declare module 'winston/test/transports/transport' {
  declare module.exports: any;
}

declare module 'winston/test/transports/webhook-test' {
  declare module.exports: any;
}

declare module 'winston/test/winston-test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'winston/examples/couchdb.js' {
  declare module.exports: $Exports<'winston/examples/couchdb'>;
}
declare module 'winston/examples/exception.js' {
  declare module.exports: $Exports<'winston/examples/exception'>;
}
declare module 'winston/examples/raw-mode.js' {
  declare module.exports: $Exports<'winston/examples/raw-mode'>;
}
declare module 'winston/examples/webhook-post.js' {
  declare module.exports: $Exports<'winston/examples/webhook-post'>;
}
declare module 'winston/lib/winston.js' {
  declare module.exports: $Exports<'winston/lib/winston'>;
}
declare module 'winston/lib/winston/common.js' {
  declare module.exports: $Exports<'winston/lib/winston/common'>;
}
declare module 'winston/lib/winston/config.js' {
  declare module.exports: $Exports<'winston/lib/winston/config'>;
}
declare module 'winston/lib/winston/config/cli-config.js' {
  declare module.exports: $Exports<'winston/lib/winston/config/cli-config'>;
}
declare module 'winston/lib/winston/config/npm-config.js' {
  declare module.exports: $Exports<'winston/lib/winston/config/npm-config'>;
}
declare module 'winston/lib/winston/config/syslog-config.js' {
  declare module.exports: $Exports<'winston/lib/winston/config/syslog-config'>;
}
declare module 'winston/lib/winston/container.js' {
  declare module.exports: $Exports<'winston/lib/winston/container'>;
}
declare module 'winston/lib/winston/exception.js' {
  declare module.exports: $Exports<'winston/lib/winston/exception'>;
}
declare module 'winston/lib/winston/logger.js' {
  declare module.exports: $Exports<'winston/lib/winston/logger'>;
}
declare module 'winston/lib/winston/transports.js' {
  declare module.exports: $Exports<'winston/lib/winston/transports'>;
}
declare module 'winston/lib/winston/transports/console.js' {
  declare module.exports: $Exports<'winston/lib/winston/transports/console'>;
}
declare module 'winston/lib/winston/transports/file.js' {
  declare module.exports: $Exports<'winston/lib/winston/transports/file'>;
}
declare module 'winston/lib/winston/transports/http.js' {
  declare module.exports: $Exports<'winston/lib/winston/transports/http'>;
}
declare module 'winston/lib/winston/transports/transport.js' {
  declare module.exports: $Exports<'winston/lib/winston/transports/transport'>;
}
declare module 'winston/lib/winston/transports/webhook.js' {
  declare module.exports: $Exports<'winston/lib/winston/transports/webhook'>;
}
declare module 'winston/test/cli-test.js' {
  declare module.exports: $Exports<'winston/test/cli-test'>;
}
declare module 'winston/test/container-test.js' {
  declare module.exports: $Exports<'winston/test/container-test'>;
}
declare module 'winston/test/custom-timestamp-test.js' {
  declare module.exports: $Exports<'winston/test/custom-timestamp-test'>;
}
declare module 'winston/test/exception-test.js' {
  declare module.exports: $Exports<'winston/test/exception-test'>;
}
declare module 'winston/test/fixtures/scripts/default-exceptions.js' {
  declare module.exports: $Exports<'winston/test/fixtures/scripts/default-exceptions'>;
}
declare module 'winston/test/fixtures/scripts/exit-on-error.js' {
  declare module.exports: $Exports<'winston/test/fixtures/scripts/exit-on-error'>;
}
declare module 'winston/test/fixtures/scripts/log-exceptions.js' {
  declare module.exports: $Exports<'winston/test/fixtures/scripts/log-exceptions'>;
}
declare module 'winston/test/fixtures/scripts/unhandle-exceptions.js' {
  declare module.exports: $Exports<'winston/test/fixtures/scripts/unhandle-exceptions'>;
}
declare module 'winston/test/helpers.js' {
  declare module.exports: $Exports<'winston/test/helpers'>;
}
declare module 'winston/test/log-exception-test.js' {
  declare module.exports: $Exports<'winston/test/log-exception-test'>;
}
declare module 'winston/test/log-rewriter-test.js' {
  declare module.exports: $Exports<'winston/test/log-rewriter-test'>;
}
declare module 'winston/test/logger-test.js' {
  declare module.exports: $Exports<'winston/test/logger-test'>;
}
declare module 'winston/test/transports/console-test.js' {
  declare module.exports: $Exports<'winston/test/transports/console-test'>;
}
declare module 'winston/test/transports/file-maxfiles-test.js' {
  declare module.exports: $Exports<'winston/test/transports/file-maxfiles-test'>;
}
declare module 'winston/test/transports/file-maxsize-test.js' {
  declare module.exports: $Exports<'winston/test/transports/file-maxsize-test'>;
}
declare module 'winston/test/transports/file-test.js' {
  declare module.exports: $Exports<'winston/test/transports/file-test'>;
}
declare module 'winston/test/transports/transport.js' {
  declare module.exports: $Exports<'winston/test/transports/transport'>;
}
declare module 'winston/test/transports/webhook-test.js' {
  declare module.exports: $Exports<'winston/test/transports/webhook-test'>;
}
declare module 'winston/test/winston-test.js' {
  declare module.exports: $Exports<'winston/test/winston-test'>;
}
