name: Pryv-registration-server CI

on: 
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
jobs:
  build:

    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [12.13]

    steps:
    - name: Download master branch
      uses: actions/checkout@v2
    
    - name: Setup Node.js with version ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: yarn setup
      run: yarn setup
      
    - name: yarn install
      run: yarn install
      
    - name: yarn database
      run: yarn database
    
    - name: yarn test
      run: yarn test