name: Pryv-registration-server CI

on: 
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
jobs:
  build:

    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [12.13]

    steps:
    - name: Download master branch
      uses: actions/checkout@v2
    
    - name: Install Node.js with version ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        
    # there is one private package (lib-release) used as npm package, so we need 
    # to authenticate
    - name: Login to github
      uses: webfactory/ssh-agent@v0.4.1
      with:
        ssh-private-key: ${{ secrets.SSH_PRYV_PRIVATE_KEY }}

    - name: yarn setup
      run: yarn setup
      
    - name: yarn install
      run: yarn install
      
    - name: yarn database
      run: yarn database
    
    - name: yarn test
      run: yarn test