name: Service-register CI

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
jobs:
  run-tests:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - name: Install `just`
      uses: extractions/setup-just@v1

    - name: Download master branch
      uses: actions/checkout@v2

    - name: Install Node.js with version ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    # there is one private package (lib-release) used as npm package, so we need
    # to authenticate
    - name: Login to github
      uses: webfactory/ssh-agent@v0.4.1
      with:
        ssh-private-key: ${{ secrets.TECH_PRYV_SSH_KEY }}

    - name: Install Redis
      run: just setup-dev-env

    - name: Install dependencies
      run: just install-stable

    - name: Start Redis
      run: just start-db

    - name: Run tests
      run: just test
