name: Pryv-registration-server deployment workflow

on: 
  push:
    branches:
      - feature/worflow-pipeline
jobs:
  build:

    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [12.13]

    steps:
    - name: Download master branch
      uses: actions/checkout@v2
    
    - name: Setup Node.js with version ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
      
    - name: yarn install
      run: yarn install
      
    - name: yarn setup
      run: yarn setup

    - name: yarn database
      run: yarn database
    
    - name: yarn test - This should never fail and could be skipped
      run: yarn test
      
    - name: yarn release
      run: yarn release

    - name: Login to the docker containers registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.REGISTRY_PRYV_SERVER }}
        username: ${{ secrets.REGISTRY_PRYV_USERNAME }}
        password: ${{ secrets.REGISTRY_PRYV_PASSWORD }}

    - name: Download base image and change the tag
      run: |
        docker pull ${{ secrets.REGISTRY_PRYV_SERVER }}/pryv/base:1.3.40
        docker tag "${{ secrets.REGISTRY_PRYV_SERVER }}/pryv/base:1.3.40" "pryv/base:1.3.40"
        
    - name: Build and deploy
      run: |
        cd build 
        ./build
        docker images