name: Pryv-registration-server deployment CD

on: 
  push:
    tags:
      - '*'

jobs:
  build:

    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [12.13]

    steps:
    - uses: actions/checkout@v2
    - name: Deployment pipeline
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: yarn setup
      run: yarn setup
      
    - name: yarn install
      run: yarn install
      
    - name: yarn database
      run: yarn database
    
    - name: yarn test - This should never fail and could be skipped
      run: yarn test
      
    - name: Build and deploy
      run: cd build && ./build