name: Pryv-registration-server deployment worflow

on: 
  push:
    branches:
      - feature/worflow-pipeline
jobs:
  build:

    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [12.13]

    steps:
    - uses: actions/checkout@v2
    - name: Deployment pipeline
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: yarn setup
      run: yarn setup
      
    - name: yarn install
      run: yarn install
      
    - name: yarn release
      run: yarn release
      
    - name: Prepare for the build
      run: |
        tar cf build/release.tar --exclude .git --exclude node_modules --exclude build .
        popd
      
    - uses: azure/docker-login@v1
    - name: Build and deploy registry container
      with:
        login-server: ${{ secrets.REGISTRY_PRYV_SERVER }}
        username: ${{ secrets.REGISTRY_PRYV_USERNAME }}
        password: ${{ secrets.REGISTRY_PRYV_PASSWORD }}

    - run: |
        cd register
        cp ../release.tar .
        docker build -f Dockerfile -t pryv/register:6.6.6-delete .
        docker tag "pryv/register:6.6.6-delete" "${{ secrets.REGISTRY_PRYV_SERVER }}/pryv/register:6.6.6-delete"
        cd ..
        
    - uses: azure/docker-login@v1
    - name: Build and deploy DNS container
      with:
        login-server: ${{ secrets.REGISTRY_PRYV_SERVER }}
        username: ${{ secrets.REGISTRY_PRYV_USERNAME }}
        password: ${{ secrets.REGISTRY_PRYV_PASSWORD }}

    - run: |
        cd dns
        cp ../release.tar .
        sudo docker build -f Dockerfile -t pryv/dns:6.6.6-delete .
        docker tag "pryv/dns:6.6.6-delete" "${{ secrets.REGISTRY_PRYV_SERVER }}/pryv/dns:6.6.6-delete"
        cd ..