name: Pryv.io register release

on: 
  push:
    tags:
      - '*'

jobs:
  release:

    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [12.13]

    steps:
    - name: Download master branch
      uses: actions/checkout@v2
    
    - name: Install Node.js with version ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
      
    # there is one private package (lib-release) used as npm package, so we need 
    # to authenticate
    - name: Login to github
      uses: webfactory/ssh-agent@v0.4.1
      with:
        ssh-private-key: ${{ secrets.TECH_PRYV_SSH_KEY }}

    - name: Download dependencies
      run: yarn

    - name: Download Redis
      run: yarn setup
      
    - name: Start database
      run: yarn database
    
    - name: Run tests
      run: yarn test
      
    - name: Transpile flowtype
      run: yarn release

    - name: Login to the docker containers registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.REGISTRY_PRYV_SERVER }}
        username: ${{ secrets.REGISTRY_PRYV_USERNAME }}
        password: ${{ secrets.REGISTRY_PRYV_PASSWORD }}

    - name: Download base image and change the tag
      run: |
        docker pull ${{ secrets.REGISTRY_PRYV_SERVER }}/pryvio/base:1.3.40
        docker tag "${{ secrets.REGISTRY_PRYV_SERVER }}/pryvio/base:1.3.40" "pryvio/base:1.3.40"
        
    - name: Build and deploy
      run: |
        cd build 
        ./build